name: Make a release

on:
  release:
    types: [published, created, edited]
  push:
    branches: [develop]
    

jobs:
  decision:
    runs-on: ubuntu-latest
    outputs:
      build: ${{ steps.decision.outputs.build }}
    steps:
      - uses: actions/checkout@v2

      - name: show info
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "$GITHUB_CONTEXT"
          
      - name: logic deciding build
        id: decision
        run: |
          echo ${{ github.ref }}
          tag=${{ github.ref }}
          marker=${tag##*-}
          echo $marker
          if [[ $marker = "red" ]];
          then
            echo red pill
            echo "::set-output name=build::red"
          elif [[ $marker = "blue" ]];
          then
            echo blue pill
            echo "::set-output name=build::blue"
          fi
          
      - name: logic on previous output
        run: |
          echo "selected build path: ${{ steps.decision.outputs.build }}"

#       - name: Upload blue artifact
#         uses: actions/upload-artifact@v1
#         with:
#           name: blue
#           path: blue_artifact
        
  red:
    needs: decision    
    if: ${{ needs.decision.outputs.build == 'red' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Upload red artifact
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.assets_url }} 
          asset_name: red
          assert_path: red_artifact        
          asset_content_type: application/zip
          
  blue:
    needs: decision    
    if: ${{ needs.decision.outputs.build == 'blue' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Upload blue artifact
        uses: actions/upload-artifact@v1
        with:
          name: blue
          path: blue_artifact  
        
